### ISSUE TITLE
Make dead player tab red when dead

### ISSUE THREAD

**Issue by Jokewa** [SBBTracker/SBBTracker#15]
https://github.com/SBBTracker/SBBTracker/blob/9d57e53749fe3a6da9dfd10bce696a5f7ab56043/src/application.py#L119

If we update a dead players tab to be red it increases visibility, could not experiment with colors since I couldn't build it myself.

With color change "*DEAD*" might not need to be added and tab layout will not change during game if it isn't

player_tab.update(title=title, background_color="red" )

**Comment by andrewrasch** [comment]
I think this was always the goal but I got distracted by other things. I'll look into this and hopefully get it into the next release.

**Comment by andrewrasch** [comment]
So coming back to this PySimpleGUI doesn't like changing the colors of things on the fly. Will probably require some more digging into the underlying TKinter code or a change to a different GUI engine (unsure if/when that will happen)

**Comment by immerzen** [comment]
I did some digging and found this. Hope it helps in some way:
https://pysimplegui.readthedocs.io/en/latest/#updating-elements-changing-elements-values-in-an-active-window
