### ISSUE TITLE
Players Conceding

### ISSUE THREAD

**Issue by kuro1989** [SBBTracker/SBBTracker#17]
Sorry new to using this site so not sure if this is the place for this, but I was in the last 2 spots of a match and the other player conceded. The tracker took the match down as a 2nd place victory instead of a 1st. Great tool over all and I'm looking forward to using this.

**Comment by andrewrasch** [comment]
Very weird. If you (or anyone else) encounters this bug again, could you upload the log file for the game? It should be located at C:\Users\<Your Windows Name>\AppData\LocalLow\Good Luck Games\Storybook Brawl\Player.log
