### ISSUE TITLE
Avast picking up as trojan malware

### ISSUE THREAD

**Issue by muffinmanifesto** [SBBTracker/SBBTracker#22]
Avast detects Win64:MalwareX-gen [Trj] when trying to run new version.

**Comment by andrewrasch** [comment]
Thanks for letting me know. I'll submit a false positive report to avast (obviously this isn't a trojan, the source is all available)

**Comment by muffinmanifesto** [comment]
Yes, sorry, I know :)

**Comment by muffinmanifesto** [comment]
I also submitted false positive

**Comment by andrewrasch** [comment]
Avast is whitelisting the file. Closing this ticket.
