### ISSUE TITLE
breaking bug preventing app from starting. stats.csv became corrupted and i had to delete

### ISSUE THREAD

**Issue by mdib1** [SBBTracker/SBBTracker#27]
SBB Tracker would not launch for me. 
It would throw the error "pandas.errors.EmptyDataError: No columns to parse from file" and crash.

I checked my statsfile and saw it had no data inside, deleting the file allowed the program to launch successfully again.

I don't know how the file became corrupted but I didn't do anything other than use the app normally.

**Comment by andrewrasch** [comment]
I don't think you're the first to have a corruption like this (though I've seen it for settings files not the stats). I'll add better handling for error states, and also see if I can stop this corruption in the first place. Thanks for letting me know.

**Comment by andrewrasch** [comment]
Fixed in v3.1.0
