### ISSUE TITLE
Add an option to disable "Hide/show tracker" button

### ISSUE THREAD

**Issue by Hohol** [SBBTracker/SBBTracker#31]
I don't need this button sitting in the corner of the screen all the time. I already have the button that shows tracker to me - it's in the Windows taskbar.
I would be fine with completely removing this button. But if someone needs it, can you at least add an option to hide it? Or hide it when the game is not running.

**Comment by andrewrasch** [comment]
So I have mulled over whether to make it optional in the past. On one hand if you don't use the button, it is somewhat useless to have it there (the button is mostly useful for those playing with 1 monitor). However it occurred to me that it has a double feature, its also actually an indicator that the overlay is actually working. I suppose that if you want to disable it that's a personal choice, I'll probably add a toggle for it in the next release.

**Comment by andrewrasch** [comment]
Added in v3.3.0
