### ISSUE TITLE
Bug: Today filter incorrect

### ISSUE THREAD

**Issue by jacksonrnewhouse** [SBBTracker/SBBTracker#39]
The date filters aren't working. It's 6:28PM in USA/Los_Angeles, and "Today" only shows yesterday's matches. I've played Hoard Dragon twice today.
![sbb bug](https://user-images.githubusercontent.com/8681133/148151133-9979376a-4bf4-4c66-8658-56a1722846d7.png)

**Comment by jacksonrnewhouse** [comment]
through the magic of turning it off and turning it back on this has resolved. Also, I realized it was all filters, not just the time ones, so it just got stuck somehow.

**Comment by andrewrasch** [comment]
I calculate the filter dates at startup so I should probably have a more dynamic way of doing so, so that people can leave the tracker open for extended periods
