### ISSUE TITLE
Would you like to update? Bug

### ISSUE THREAD

**Issue by Kensey007** [SBBTracker/SBBTracker#46]
For the past several days, the tracker says "An update is available! Would you like to install? Yes Remind Me Later."

If I click Yes, nothing happens.

**Comment by andrewrasch** [comment]
Hi Kensey,

There was a bug for that version of the tracker that broke the updater.
You'll have to go to the releases page, download the latest release, and
install it. The update should work as normal after that. Apologies for the
inconvenience.
