### ISSUE TITLE
Calculations for sims of Tweedle Dee misunderstand stats on respawn

### ISSUE THREAD

**Issue by v-padum** [SBBTracker/SBBTracker#49]
The simulations that run on Tweedle Dee don't see to understand the stats that Tweedle Dum will have (missing attack from supports, probably?) (and specifically also how they interact with Echowood as well), and as a result, seems to misrepresent win rates for boards that contain it. In this very dorf meta, this is a problem.

**Comment by isikdos** [comment]
Handy report, helped us find the bug -- positive buffs like Sting were applying while tweedle dum was still seen as a 0/0, so after an attack-only buff, tweedle dum would be an X/0 and then immediately marked for death.

Fix going out soon

**Comment by andrewrasch** [comment]
Fixed in 4.2.0
