### ISSUE TITLE
Last seen boards are cropping off in windowed mode

### ISSUE THREAD

**Issue by ShimSekai** [SBBTracker/SBBTracker#50]
![SBBTracker_2022-02-28_06-48-29](https://user-images.githubusercontent.com/27683354/155963343-94697c17-da49-4d4d-b7dd-bfee4603f706.jpg)

**Comment by andrewrasch** [comment]
You can adjust the size of the overlay in Settings > Overlay > Board Comps Scaling. If you bring that to below 100 (maybe something like 80 or 90 will work for you) it should fit on the screen better
