### ISSUE TITLE
Tracker Displays Incorrect Starting Hero When Dreaming to Grandmother at 6

### ISSUE THREAD

**Issue by TheRealHasNoName2** [SBBTracker/SBBTracker#69]
Happened twice now (with different starting heros, waddle and snow angel) so should be reproducible.  I dreamed when already level 6 into Grandmother and the tracker says my starting hero was big bad wolf and my ending hero is grandmother.

**Comment by andrewrasch** [comment]
should be fixed in v4.12.3
